---
# tasks file for freeswitch-mw

- include_vars: "../vars/{{ ansible_os_family }}.yml"

# Setup/install tasks.
- include: setup-Debian.yml
  when: ansible_distribution == 'Debian' and ansible_distribution_release == 'jessie'

